yatube_project/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list')
]

yatube_project/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
     path('logout/',LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),
     path('signup/', views.SignUp.as_view(), name='signup'),
     path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
]

yatube_project/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube_project/about/models.py
from django.db import models

# Create your models here.

yatube_project/posts/models.py
from django.db import models

from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.TextField()
    slug = models.SlugField()
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='posts'
    )

    def __str__(self):
        return self.text

yatube_project/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()

class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', "username", 'email')

yatube_project/about/views.py
from django.shortcuts import render

# Create your views here.

yatube_project/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from .models import Group, Post
from django.shortcuts import redirect

def authorized_only(func):
    def check_user(request, *args, kwargs):
        if request.user.is_authenticated:
            return func(request, *args, *kwargs)
        return redirect('/auth/login/')
    return check_user


def index(request):
    post_list = Post.objects.order_by('-pub_date')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'title' : 'Последние обновления на сайте',
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    title = 'Записи группы '
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'title': title + group.title,
        'posts': posts,
        'description': group.description,
    }
    return render(request, 'posts/group_list.html', context)

yatube_project/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from users.forms import CreationForm

# Create your views here.

class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube_project/templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href={% static "img/fav/favicon.ico" %}  type="image" >
    <link rel="apple-touch-icon" sizes="180x180" href={% static "img/fav/apple-touch-icon.png"%}>
    <link rel="icon" type="image/png" sizes="32x32" href={% static "img/fav/favicon-32x32.png"%}>
    <link rel="icon" type="image/png" sizes="16x16" href={% static "img/fav/favicon-16x16.png"%}>
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <title>
        {%block title%}{%endblock%}
    </title>
    <link rel="stylesheet" href={% static 'bootstrap/dist/css/bootstrap.min.css'%}>
    <script src="{% static 'jquery/dist/jquery.min.js' %}"> </script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"> </script>
  </head>
  <body>
    <header>
        {% include "includes/header.html" %}
    </header>
    <main>
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h1>{%block title_h1%}{%endblock%}</h1>
        {% block content %}
        {% endblock %}
      </div>  
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отсупом сверху и снизу -->         
    <footer class="border-top text-center py-3">
        {% include "includes/footer.html" %}
    </footer>
  </body>
</html>

yatube_project/templates/includes/footer.html
<!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
<p>© 2024 Copyright <span style="color:red">Ya</span>tube</p>    

yatube_project/templates/includes/header.html
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
           <!-- ссылка должна вести на главную страницу -->
          <a class="navbar-brand" href="{% url 'posts:index' %}">
            {% load static %}
            <img src={% static "img/logo.png"%} width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube
          </a>
        </div>
      </nav>     

yatube_project/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
<ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая </a> </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Предыдущая
            </a>
        </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
            <li class="page-item active">
                <span class="page-link">{{ i }} </span>
            </li>
        {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }} </a>
            </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Следующая
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                Последняя
            </a>
        </li>
    {% endif %}
    </ul>
</nav>
{% endif %} 

yatube_project/templates/posts/group_list.html
{% extends 'base.html' %}
{%block title%}{{title}}{%endblock%}
{%block title_h1%}{{title}}{%endblock%}
{% block content %}
<p>{{description}}</p>
{% for post in posts %}
<article>
    <ul>
        <li>
            Автор: {{ post.author.get_username }}
        </li>
        <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
    </ul>
    <p>{{ post.text }} </p>
</article>
<hr>
</hr>
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% endblock %}

yatube_project/templates/posts/index.html
{% extends 'base.html' %}
{%block title%}{{title}}{%endblock%}
{%block title_h1%}{{title}}{%endblock%}
{% block content %}
{% if user.is_authenticated %}
{% for post in page_obj %}
<ul>
    <li>
        Автор: {{ post.author.get_username }}
    </li>
    <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
</ul>
<p>{{ post.text }} </p>
{% if not post.group == null %}<a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы </a>{% endif %}
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'includes/paginator.html' %}
{% else %}
{{'Вы не авторизованы'}}
{% endif %}
{% endblock %}

yatube_project/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
                Выход
            </div>
            <div class="card-body">
                <p>Вы вышли из своей учётной записи. Ждём вас снова!</p>
            </div> 
        </div> 
    </div> 
</div> 
{% endblock %} 

yatube_project/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{%block content%}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Войти на сайт</div>
            <div class="card-body">
                {% load user_filters %} {# Загружаем фильтры #}
                {# Этот блок будет показан, если в форме есть ошибки #}
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            {{ error|escape }}
                        </div>
                    {% endfor %}
                {% endif %}
                    <form method="post">
                        {% if action_url %}
                            action="{% url action_url %}"
                        {% endif %}
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group row my-3 p-3">
                            <label for="{{ field.id_for_label }}">
                                {{ field.label }}
                                {% if field.field.required %}
                                    <span class="required text-danger">* </span>
                                {% endif %}
                            </label>
                        {# К полю ввода добавляем атрибут class #}
                        {{ field|addclass:'form-control' }} 
                        {% if field.help_text %}
                            <small id="{{ field.id_for_label }}-help" class="formtext text-muted">
                                {{ field.help_text|safe }}
                            </small>
                        {% endif %}
                        </div>
                        {% endfor %}
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                Войти
                            </button>
                        </div>
                    </form>
                </div> 
            </div> 
        </div> 
    </div> 
   {% endblock %} 

yatube_project/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{%block content%}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Зарегистрироваться</div>
            <style>
                .card-header {
                    text-align:  center;
                }
            </style>
            <div class="card-body">
                {% load user_filters %} {# Загружаем фильтры #}
                {# Этот блок будет показан, если в форме есть ошибки #}
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            {{ error|escape }}
                        </div>
                    {% endfor %}
                {% endif %}
                    <form method="post" action="{% url 'users:signup' %}">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group row my-3 p-3">
                            <label for="{{ field.id_for_label }}">
                                {{ field.label }}
                                {% if field.field.required %}
                                    <span class="required text-danger">* </span>
                                {% endif %}
                            </label>
                        {# К полю ввода добавляем атрибут class #}
                        {{ field|addclass:'form-control' }} 
                        {% if field.help_text %}
                            <small id="{{ field.id_for_label }}-help" class="formtext text-muted">
                                {{ field.help_text|safe }}
                            </small>
                        {% endif %}
                        </div>
                        {% endfor %}
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                Зарегистрироваться
                            </button>
                        </div>
                    </form>
                </div> 
            </div> 
        </div> 
    </div> 
   {% endblock %} 